name: 'Backpack'
description: 'Saves articles as Markdown files.'
author: 'fparga'
branding:
  icon: 'anchor'
  color: 'blue'

inputs:
  url:
    required: true
    description: 'URL of the article to save'

runs:
  using: 'node12'
  main: 'dist/index.js'
